In [1]:
import os
from datetime import datetime
from sys import exit
import pickle
import random
import math
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.colors as mcolors
import matplotlib.pyplot as plt

from re import X

from sklearn.preprocessing import StandardScaler, MaxAbsScaler, MinMaxScaler

import torch
import torch.nn as nn
import torch.nn.functional as F

os.makedirs("models", exist_ok=True)
os.makedirs("ensemble_models", exist_ok=True)

def set_all_seeds(seed):
    np.random.seed(seed)
    print(f"Random Seed: {seed}")
    random.seed(seed)
    torch.manual_seed(seed)

seed = 0
set_all_seeds(seed)

Random Seed: 0

In [2]:

df = pd.read_csv(f"BTCUSDT-15m-data.csv")
print(df.head())

             timestamp      open_time     open     high      low    close  \
0  2017-08-17 04:00:00  1502942400000  4261.48  4280.56  4261.48  4261.48
1  2017-08-17 04:15:00  1502943300000  4261.48  4270.41  4261.32  4261.45
2  2017-08-17 04:30:00  1502944200000  4280.00  4310.07  4267.99  4310.07
3  2017-08-17 04:45:00  1502945100000  4310.07  4313.62  4291.37  4308.83
4  2017-08-17 05:00:00  1502946000000  4308.83  4328.69  4304.31  4304.31

      volume     close_time      quote_av  trades  tb_base_av   tb_quote_av  \
0   2.189061  1502943299999   9333.620962       9    0.489061   2089.104962
1   9.119865  1502944199999  38891.133046      40    3.447113  14703.934995
2  21.923552  1502945099999  94080.917568      58   20.421317  87620.977876
3  13.948531  1502945999999  60060.466816      64   10.803012  46538.460109
4   5.101153  1502946899999  22006.533111      44    3.496635  15093.783057

   ignore
0       0
1       0
2       0
3       0
4       0

In [3]:
df.count()

timestamp      276000
open_time      276000
open           276000
high           276000
low            276000
close          276000
volume         276000
close_time     276000
quote_av       276000
trades         276000
tb_base_av     276000
tb_quote_av    276000
ignore         276000
dtype: int64

In [4]:
df.tail()

,timestamp,open_time,open,high,low,close,volume,close_time,quote_av,trades,tb_base_av,tb_quote_av,ignore
275995,2025-07-07 00:00:00,1751846400000,109203.85,109273.07,109103.19,109273.06,56.48447,1751847299999,6.166301e+06,26415,26.22332,2.862917e+06,0
275996,2025-07-07 00:15:00,1751847300000,109273.07,109288.02,108972.69,109004.81,75.36437,1751848199999,8.220317e+06,24191,33.56157,3.660548e+06,0
275997,2025-07-07 00:30:00,1751848200000,109004.81,109037.82,108829.17,108847.16,76.72080,1751849099999,8.357724e+06,21368,33.08997,3.605029e+06,0
275998,2025-07-07 00:45:00,1751849100000,108847.17,108922.00,108800.01,108823.07,45.06548,1751849999999,4.906468e+06,15579,22.76836,2.478881e+06,0
275999,2025-07-07 01:00:00,1751850000000,108823.07,108823.08,108679.75,108767.01,75.71845,1751850899999,8.232864e+06,22928,38.85713,4.224608e+06,0

In [5]:
print(df.isnull())
print(f'Counts how many missing values there are in each column: {df.isnull().sum()}')
print(f'Total missing values: {df.isnull().sum().sum()}')

        timestamp  open_time   open   high    low  close  volume  close_time  \
0           False      False  False  False  False  False   False       False
1           False      False  False  False  False  False   False       False
2           False      False  False  False  False  False   False       False
3           False      False  False  False  False  False   False       False
4           False      False  False  False  False  False   False       False
...           ...        ...    ...    ...    ...    ...     ...         ...
275995      False      False  False  False  False  False   False       False
275996      False      False  False  False  False  False   False       False
275997      False      False  False  False  False  False   False       False
275998      False      False  False  False  False  False   False       False
275999      False      False  False  False  False  False   False       False

        quote_av  trades  tb_base_av  tb_quote_av  ignore
0          False   False       False        False   False
1          False   False       False        False   False
2          False   False       False        False   False
3          False   False       False        False   False
4          False   False       False        False   False
...          ...     ...         ...          ...     ...
275995     False   False       False        False   False
275996     False   False       False        False   False
275997     False   False       False        False   False
275998     False   False       False        False   False
275999     False   False       False        False   False

[276000 rows x 13 columns]
Counts how many missing values there are in each column: timestamp      0
open_time      0
open           0
high           0
low            0
close          0
volume         0
close_time     0
quote_av       0
trades         0
tb_base_av     0
tb_quote_av    0
ignore         0
dtype: int64
Total missing values: 0

#Training Phase

Splitting data to train/test sets

Practice same pattersn multiple times

Have access to answer key

problems known:
Overfitting
Underfitting

#Testing Phase

Face new Patterns

No access to asnwer key

In [6]:
df[['open', 'high', 'low', 'close', 'volume']].head()

      open     high      low    close     volume
0  4261.48  4280.56  4261.48  4261.48   2.189061
1  4261.48  4270.41  4261.32  4261.45   9.119865
2  4280.00  4310.07  4267.99  4310.07  21.923552
3  4310.07  4313.62  4291.37  4308.83  13.948531
4  4308.83  4328.69  4304.31  4304.31   5.101153

In [7]:

df['open'].dtypes

dtype('float64')

In [8]:
df['open_time'].diff().dropna().value_counts().head()

open_time
900000.0     275966
4500000.0         5
8100000.0         3
1800000.0         2
7200000.0         2
Name: count, dtype: int64

In [9]:
# what is a feature:
# a Mesurable piece of information that describe the data
# help the model to recognize patterns

#always pay attention to the shape of the data

def compute_moving_average(prices, window):
    values = np.full(len(prices), np.nan, dtype=np.float64)
    for i in range(window - 1, len(prices)):
        values[i] = prices[i - window + 1:i + 1].mean()  # FIX: mean, not max
    return values

def compute_moving_std(prices, window):
    values = np.full(len(prices), np.nan, dtype=np.float64)
    for i in range(window - 1, len(prices)):
        values[i] = prices[i - window + 1:i + 1].std()
    return values

def build_feature(opens, highs, lows, closes, volumes, train_scalers=None):

    #EPSILON
    eps = 1e-12

    #build features
    #candle shape features (normalized)
    feature1 = (closes - opens) / (opens + eps)
    feature2 = (highs - opens) / (opens + eps) # how much price rose above the open
    feature3 = (highs - closes) / (closes + eps) # how far the close was below the high
    feature4 = (lows - opens) / (opens + eps) # how much price fell below the open

    # “How far the low was below the close” (lower wick strength)
    feature5 = (closes - lows) / (closes + eps)

    feature6 = (highs - lows) / (opens + eps) # the day's volatility range relative to open
    feature7 = (highs - lows) / (closes + eps) # the day's volatility range relative to close

    # Volume: heavy-tailed -> stabilize
    feature8 = np.log1p(volumes)

    # MA deviation + volatility
    close_ma_5 = compute_moving_average(closes, 5)
    feature9 = (closes - close_ma_5) / (close_ma_5 + eps)

    feature10 = compute_moving_std(closes, 5)

    # Stack features
    features = [
      feature1, feature2,
      feature3, feature4,
      feature5, feature6,
      feature7, feature8,
      feature9, feature10
    ]

    # Drop rows with NaN (from rolling features)
    feat_mat = np.stack(features, axis=-1)  # (m, 10)
    valid_mask = ~np.isnan(feat_mat).any(axis=1)

    #feature matrix shape(m, 10) 10 = n features
    feat_mat = feat_mat[valid_mask]

    num_features = feat_mat.shape[1]

    scaled_fts = []

    if train_scalers is None:
      train_scalers = [MaxAbsScaler() for _ in range(num_features)]
      is_train = True
    else:
      is_train = False

    scaled_cols = []
    for i in range(num_features):
        col = feat_mat[:, i].reshape(-1, 1)
        scaler = train_scalers[i]
        if is_train:
            col_s = scaler.fit_transform(col)
        else:
            col_s = scaler.transform(col)
        scaled_cols.append(col_s.reshape(-1))

    scaled_features = np.stack(scaled_cols, axis=-1)  # (m_valid, 10)
    return scaled_features, num_features, train_scalers, valid_mask

In [10]:
# # This list will store each feature AFTER scaling
# # Each element will be a 1D array (one column / one feature)
# scaled_cols = []

# # Loop through each feature (column-wise scaling)
# for i in range(num_features):

#     # Extract ONE feature column from the feature matrix
#     # feat_mat shape: (num_rows, num_features)
#     # col shape becomes: (num_rows, 1)
#     # We reshape because sklearn scalers expect 2D input
#     col = feat_mat[:, i].reshape(-1, 1)

#     # Get the scaler corresponding to this feature
#     # Each feature has its own scaler to avoid mixing distributions
#     scaler = train_scalers[i]

#     if is_train:
#         # TRAINING MODE
#         # fit_transform():
#         # 1) LEARNS the scaling parameters (e.g. max value)
#         # 2) APPLIES the scaling to the training data
#         # This MUST happen ONLY on training data to avoid data leakage
#         col_s = scaler.fit_transform(col)

#     else:
#         # TESTING / INFERENCE MODE
#         # transform():
#         # Uses the SAME parameters learned from training
#         # IMPORTANT: We do NOT re-learn anything here
#         # This simulates real live trading where future data is unseen
#         col_s = scaler.transform(col)

#     # Flatten back to 1D so we can stack columns later
#     scaled_cols.append(col_s.reshape(-1))

# # Stack all scaled feature columns back together
# # Resulting shape: (num_rows, num_features)
# # Each row = one candle
# # Each column = one scaled feature
# scaled_features = np.stack(scaled_cols, axis=-1)

# # Return:
# # scaled_features → clean, scaled input for the model
# # num_features    → number of input features (used by the model)
# # train_scalers   → saved scalers (needed for test/live data)
# # valid_mask      → tells which original rows were kept (after NaN removal)
# return scaled_features, num_features, train_scalers, valid_mask


Summary table (easy recall)
Choice	Why
to_numpy()	Clean pandas → NumPy conversion
float64 (features)	Accurate math, stable rolling stats
float32 (X, Y)	Fast ML training, GPU friendly
m = len(features)	Only valid rows count
samples	Sliding windows, not candles
num_samples	Prevent leakage & index errors


One-sentence mental model
Clean and compute precisely first (float64), then train efficiently (float32), always counting only valid data.

In [10]:
def preprocessing_data(seq_len, df, train_scalers=None, horizon=4):

    # seq_len=96: input window (24h for 15m)
    # horizon=4: predict 1-hour forward return (4*15m)

    opens   = df['open'].to_numpy(dtype=np.float64)
    highs   = df['high'].to_numpy(dtype=np.float64)
    lows    = df['low'].to_numpy(dtype=np.float64)
    closes  = df['close'].to_numpy(dtype=np.float64)
    volumes = df['volume'].to_numpy(dtype=np.float64)

    # Build features
    features, num_features, train_scalers, valid_mask = build_feature(opens, highs, lows, closes, volumes, train_scalers)

    # Align opens/closes with the same valid_mask used for features
    opens_valid = opens[valid_mask]
    closes_valid = closes[valid_mask]


    #Number of valid time steps after feature construction.
    m = len(features)
    num_samples = m - seq_len - horizon
    if num_samples <= 0:
        raise ValueError("Not enough data after dropping NaNs for chosen seq_len/horizon.")

    #create storage for input & targets
    # x the input sequence
    # y the output/target
    X = np.zeros((num_samples, seq_len, num_features), dtype=np.float32)
    Y = np.zeros((num_samples, 1), dtype=np.float32)  # FIX: regression target is 1 value
    opens_bt  = np.zeros(num_samples, dtype=np.float64)
    closes_bt = np.zeros(num_samples, dtype=np.float64)

    for i in range(num_samples):
        X[i] = features[i:i+seq_len]

        # FUTURE LOG RETURN target at the prediction point
        t = i + seq_len
        opens_bt[i]  = opens_valid[t] #price at decision time (when model acts)
        closes_bt[i] = closes_valid[t + horizon] #price after holding for horizon candles

        y = np.log(closes_valid[t + horizon] / closes_valid[t])
        Y[i, 0] = y

    return X, Y, opens_bt, closes_bt, num_features, train_scalers

Return prices at the same timestamps your model predicts on — never raw dataframe prices.

In [11]:
# Output matches regression target (B,1)

#  Avoids flattening (64*96) which overfits

#  Residual improves training stability

#  Fast, strong baseline for candles


class Model(nn.Module):
    def __init__(self, num_features, seq_len, hidden=64, dropout=0.1):
        super().__init__()

        # Project features -> hidden channels
        self.in_proj = nn.Conv1d(num_features, hidden, kernel_size=1)

        # Two temporal conv blocks (can add more)
        self.conv1 = nn.Conv1d(hidden, hidden, kernel_size=3, padding=1)
        self.conv2 = nn.Conv1d(hidden, hidden, kernel_size=3, padding=1)

        self.act = nn.GELU()
        self.drop = nn.Dropout(dropout)

        # Regression head: use LAST timestep representation (causal-ish)
        self.fc_out = nn.Linear(hidden, 1)

    def forward(self, x):
        # x: (B, T, F)
        x = x.transpose(1, 2)          # (B, F, T)

        x = self.in_proj(x)            # (B, H, T)

        # Conv block
        y = self.act(self.conv1(x))
        y = self.drop(y)
        y = self.act(self.conv2(y))
        y = self.drop(y)

        # Residual connection helps stability
        x = x + y                      # (B, H, T)

        # Take last timestep representation
        last = x[:, :, -1]             # (B, H)

        #Regression head Converts the learned representation into: predicted future return
        #Exactly matches Y_train.shape = (N, 1)
        out = self.fc_out(last)        # (B, 1)
        return out

Conceptually, it’s just:
[96 candles]
     ↓
extract time patterns
     ↓
summarize into one vector
     ↓
predict future return

The forward function turns 96 past candles into a learned summary, then maps that summary to a future return estimate.

In [23]:
def create_minibatches(X, Y, batch_size, seed, shuffle=True):
    #mini_batches will hold a list of (mb_X, mb_Y) pairs.
    mini_batches = []

    #m = number of training samples (windows).
    m = len(X)

    #Creates a random order of indices [0..m-1].
    #Reorders X and Y the same way, so inputs still match targets.
    #Why: helps SGD/Adam generalize and not learn “the order”.

    if shuffle:
        # RNG Numpy Random Generator
        rng = np.random.default_rng(seed) # seed controls shuffle
        permutation = rng.permutation(m)
        X = X[permutation]
        Y = Y[permutation]
    #Compute how many full batches fit
    num_batches = m // batch_size
    #Slice batches
    for k in range(num_batches):
        start = k * batch_size
        end = start + batch_size
        mini_batches.append((X[start:end], Y[start:end]))


    #Seed update
    # seed += 1
    set_all_seeds(seed)

    return mini_batches, seed

One-line rule to remember

If you index NumPy arrays, keep indices as NumPy arrays.

So: do not convert perm to list()

In [24]:
from re import X
# Sequence Lenght fot the inout sequence equivalent 1 day of 15m candles
seq_len = 96
horizon = 4  # 1 hour ahead for 15m candles
num_epochs = 100

In [25]:
#Train one epoch
def train_one_epoch(model, optimizer, criterion, mini_batches):
    model.train()
    batch_losses = []

    for Xb, Yb in mini_batches:
        optimizer.zero_grad()
        pred = model(Xb)                     # (B, 1)
        loss = criterion(pred, Yb)           # scalar
        loss.backward()
        optimizer.step()
        batch_losses.append(loss.item())

    return float(np.mean(batch_losses))

model.eval() switches the network into inference mode, turning off training-only behavior (like dropout) so validation/test results are stable and meaningful.

In [26]:
#Evaluate (test loss + predictions)

@torch.no_grad()
def eval_model(model, criterion, X_test, Y_test):
    model.eval()
    pred = model(X_test)                     # (N, 1)
    loss = criterion(pred, Y_test).item()
    return loss, pred

In [27]:
#Turn regression predictions into signals (thresholded)
def predictions_to_signals(pred_return, thr):
    """
    pred_return: numpy (N,1) predicted log-return
    thr: threshold in log-return units
    returns: signals in {-1,0,+1}
    """
    p = pred_return[:, 0]
    sig = np.zeros_like(p, dtype=np.int8)
    sig[p >  thr] =  1   # long
    sig[p < -thr] = -1   # short
    return sig

In [28]:
#Backtest (aligned with our horizon strategy)
#This assumes you already return opens_bt and closes_bt from preprocessing (aligned to samples).

def backtest_signals(opens_bt, closes_bt, signals, pos_size=1000.0, fee_rate=0.0):
    """
    opens_bt[i]  = entry reference price at time t
    closes_bt[i] = exit reference price at time t+horizon
    signals[i] in {-1,0,+1}
    pos_size in USD notionals per trade

    fee_rate example:
      - If you want 0.04% taker each side: fee_rate = 0.0004
      - Round trip fees approx: 2 * fee_rate * pos_size per trade (rough)
    """
    equity = 1000.0
    equities = []
    correct = 0
    traded = 0
    n = len(signals)

    i = 0
    while i < n:
        s = signals[i]
        if s == 0:
            equities.append(equity)
            i += 1
            continue

        o = opens_bt[i]
        c = closes_bt[i]  # already aligned to t+horizon in your preprocessing
        pct_change = (c - o) / o

        pnl = s * pos_size * pct_change
        pnl -= 2.0 * fee_rate * pos_size

        equity += pnl
        equities.append(equity)

        traded += 1
        if (s == 1 and pct_change > 0) or (s == -1 and pct_change < 0):
            correct += 1

        i += horizon  # IMPORTANT: skip forward so trades don’t overlap

    accuracy = (correct / traded * 100.0) if traded > 0 else 0.0
    return equity, np.array(equities, dtype=np.float64), accuracy, traded

In [29]:
#Save checkpoint (use a new filename for new architecture)
def save_checkpoint(path, epoch, model, optimizer, train_losses, test_losses, equity_epochs, accuracy_epochs, seed):
    torch.save({
        "epoch": epoch,
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "train_losses": train_losses,
        "test_losses": test_losses,
        "equity_epochs": equity_epochs,
        "accuracy_epochs": accuracy_epochs,
        "seed": seed,
    }, path)

In [30]:
def choose_threshold_from_val(pred_val_np, q=0.90):
    # trade top 10% strongest signals
    p = pred_val_np[:,0]
    thr = np.quantile(np.abs(p), q)
    return float(thr)

In [31]:

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("my device: ", device)

my device:  cuda

In [32]:
fee_rate = 0.0005 # example placeholder (0.04%); set to 0 if you ignore fees
wf_results = []

start = 0
fold = 0
batch_size = 64

CANDLES_PER_DAY = 96
TRAIN = 365 * CANDLES_PER_DAY   # 12 months
VAL   =  90 * CANDLES_PER_DAY   # 3 months
TEST  =  90 * CANDLES_PER_DAY   # 3 months
STEP  =  TEST                   # roll 3 months

while start + TRAIN + VAL + TEST <= len(df):

    df_train = df.iloc[start : start + TRAIN].copy()
    df_val   = df.iloc[start + TRAIN : start + TRAIN + VAL].copy()
    df_test  = df.iloc[start + TRAIN + VAL : start + TRAIN + VAL + TEST].copy()

    # ---- preprocess (fit scalers on TRAIN only) ----
    X_train, Y_train, opens_tr, closes_tr, num_features, scalers = preprocessing_data(
        seq_len, df_train, train_scalers=None, horizon=horizon
    )
    X_val, Y_val, opens_val, closes_val, _, _ = preprocessing_data(
        seq_len, df_val, train_scalers=scalers, horizon=horizon
    )
    X_test, Y_test, opens_test, closes_test, _, _ = preprocessing_data(
        seq_len, df_test, train_scalers=scalers, horizon=horizon
    )

    # ---- torch tensors ----
    X_train_t = torch.from_numpy(X_train).to(device)
    Y_train_t = torch.from_numpy(Y_train).to(device)

    X_val_t   = torch.from_numpy(X_val).to(device)
    Y_val_t   = torch.from_numpy(Y_val).to(device)

    X_test_t  = torch.from_numpy(X_test).to(device)
    Y_test_t  = torch.from_numpy(Y_test).to(device)

    # ---- init a fresh model per fold (WFV requirement) ----
    model = Model(num_features=num_features, seq_len=seq_len).to(device)
    criterion = nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

    # trackers (per fold)
    train_losses, val_losses = [], []
    best_val_loss = float("inf")
    best_state = None

    # ---- TRAIN EPOCH LOOP (your loop) ----
    for epoch in range(num_epochs):
        dt0_epoch = datetime.now()

        mini_batches, seed = create_minibatches(X_train_t, Y_train_t, batch_size, seed, shuffle=True)

        train_loss = train_one_epoch(model, optimizer, criterion, mini_batches)

        # evaluate on VAL (NOT on test) during training
        val_loss, pred_val = eval_model(model, criterion, X_val_t, Y_val_t)

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        # keep best model by VAL loss (or VAL equity if you prefer)
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

        print(
            f"[Fold {fold}] Epoch {epoch:03d} | "
            f"TrainLoss {train_loss:.6g} | ValLoss {val_loss:.6g} | "
            f"Duration {datetime.now() - dt0_epoch}"
        )

    # ---- restore best model (by VAL) ----
    model.load_state_dict(best_state)
    model.to(device)
    model.eval()

    # ---- choose threshold on VAL predictions only ----
    pred_val_np = pred_val.detach().cpu().numpy()    # last val preds (or recompute)
    thr = choose_threshold_from_val(pred_val_np, q=0.90)

    #Save Model:
    fold_ckpt_path = f"models/wfv_fold_{fold}_best.pt"
    torch.save({
        "model_state_dict": model.state_dict(),
        "num_features": num_features,
        "seq_len": seq_len,
        "horizon": horizon,
        "thr": thr,   # will set after computing thr; see note below
    }, fold_ckpt_path)
    print(f"[Fold {fold}] Saved best model to {fold_ckpt_path}")

    # ---- final evaluation on TEST (OOS for this fold) ----
    test_loss, pred_test = eval_model(model, criterion, X_test_t, Y_test_t)
    pred_test_np = pred_test.detach().cpu().numpy()

    signals = predictions_to_signals(pred_test_np, thr)

    # IMPORTANT: no-overlap backtest for horizon strategy
    equity, equities, accuracy, traded = backtest_signals(
        opens_test,
        closes_test,
        signals,
        pos_size=1000.0,
        fee_rate=fee_rate
    )

    wf_results.append({
        "fold": fold,
        "start_idx": start,
        "thr": thr,
        "test_loss": test_loss,
        "equity": equity,
        "accuracy": accuracy,
        "traded": traded,
        "train_rows": len(df_train),
        "val_rows": len(df_val),
        "test_rows": len(df_test),
    })

    print(
        f"\n=== WFV Fold {fold} RESULT ===\n"
        f"Thr {thr:.6g} | TestLoss {test_loss:.6g} | "
        f"Equity {equity:,.2f} | Acc {accuracy:.2f}% | Traded {traded}\n"
    )

    # move forward
    start += STEP
    fold += 1

Streaming output truncated to the last 5000 lines.
[Fold 1] Epoch 062 | TrainLoss 0.000127459 | ValLoss 6.85122e-05 | Duration 0:00:01.118527
Random Seed: 166
[Fold 1] Epoch 063 | TrainLoss 0.000127282 | ValLoss 6.85096e-05 | Duration 0:00:01.112795
Random Seed: 166
[Fold 1] Epoch 064 | TrainLoss 0.000127105 | ValLoss 6.85069e-05 | Duration 0:00:01.118795
Random Seed: 166
[Fold 1] Epoch 065 | TrainLoss 0.000126929 | ValLoss 6.85041e-05 | Duration 0:00:01.124083
Random Seed: 166
[Fold 1] Epoch 066 | TrainLoss 0.000126753 | ValLoss 6.85013e-05 | Duration 0:00:01.271177
Random Seed: 166
[Fold 1] Epoch 067 | TrainLoss 0.000126577 | ValLoss 6.84984e-05 | Duration 0:00:01.404072
Random Seed: 166
[Fold 1] Epoch 068 | TrainLoss 0.000126402 | ValLoss 6.84954e-05 | Duration 0:00:01.105872
Random Seed: 166
[Fold 1] Epoch 069 | TrainLoss 0.000126226 | ValLoss 6.84925e-05 | Duration 0:00:01.125514
Random Seed: 166
[Fold 1] Epoch 070 | TrainLoss 0.000126051 | ValLoss 6.84895e-05 | Duration 0:00:01.113395
Random Seed: 166
[Fold 1] Epoch 071 | TrainLoss 0.000125875 | ValLoss 6.84866e-05 | Duration 0:00:01.126138
Random Seed: 166
[Fold 1] Epoch 072 | TrainLoss 0.000125699 | ValLoss 6.84837e-05 | Duration 0:00:01.118599
Random Seed: 166
[Fold 1] Epoch 073 | TrainLoss 0.000125523 | ValLoss 6.84808e-05 | Duration 0:00:01.121932
Random Seed: 166
[Fold 1] Epoch 074 | TrainLoss 0.000125347 | ValLoss 6.8478e-05 | Duration 0:00:01.099161
Random Seed: 166
[Fold 1] Epoch 075 | TrainLoss 0.00012517 | ValLoss 6.84752e-05 | Duration 0:00:01.126732
Random Seed: 166
[Fold 1] Epoch 076 | TrainLoss 0.000124993 | ValLoss 6.84726e-05 | Duration 0:00:01.228276
Random Seed: 166
[Fold 1] Epoch 077 | TrainLoss 0.000124815 | ValLoss 6.847e-05 | Duration 0:00:01.395303
Random Seed: 166
[Fold 1] Epoch 078 | TrainLoss 0.000124637 | ValLoss 6.84675e-05 | Duration 0:00:01.244423
Random Seed: 166
[Fold 1] Epoch 079 | TrainLoss 0.000124458 | ValLoss 6.8465e-05 | Duration 0:00:01.184615
Random Seed: 166
[Fold 1] Epoch 080 | TrainLoss 0.000124279 | ValLoss 6.84627e-05 | Duration 0:00:01.122210
Random Seed: 166
[Fold 1] Epoch 081 | TrainLoss 0.000124099 | ValLoss 6.84604e-05 | Duration 0:00:01.143102
Random Seed: 166
[Fold 1] Epoch 082 | TrainLoss 0.000123918 | ValLoss 6.84583e-05 | Duration 0:00:01.141742
Random Seed: 166
[Fold 1] Epoch 083 | TrainLoss 0.000123737 | ValLoss 6.84562e-05 | Duration 0:00:01.118014
Random Seed: 166
[Fold 1] Epoch 084 | TrainLoss 0.000123555 | ValLoss 6.84543e-05 | Duration 0:00:01.137718
Random Seed: 166
[Fold 1] Epoch 085 | TrainLoss 0.000123373 | ValLoss 6.84524e-05 | Duration 0:00:01.121315
Random Seed: 166
[Fold 1] Epoch 086 | TrainLoss 0.00012319 | ValLoss 6.84505e-05 | Duration 0:00:01.125227
Random Seed: 166
[Fold 1] Epoch 087 | TrainLoss 0.000123006 | ValLoss 6.84488e-05 | Duration 0:00:01.411433
Random Seed: 166
[Fold 1] Epoch 088 | TrainLoss 0.000122821 | ValLoss 6.84471e-05 | Duration 0:00:01.319853
Random Seed: 166
[Fold 1] Epoch 089 | TrainLoss 0.000122636 | ValLoss 6.84454e-05 | Duration 0:00:01.091934
Random Seed: 166
[Fold 1] Epoch 090 | TrainLoss 0.00012245 | ValLoss 6.84438e-05 | Duration 0:00:01.115746
Random Seed: 166
[Fold 1] Epoch 091 | TrainLoss 0.000122263 | ValLoss 6.84423e-05 | Duration 0:00:01.113615
Random Seed: 166
[Fold 1] Epoch 092 | TrainLoss 0.000122075 | ValLoss 6.84408e-05 | Duration 0:00:01.109383
Random Seed: 166
[Fold 1] Epoch 093 | TrainLoss 0.000121887 | ValLoss 6.84393e-05 | Duration 0:00:01.111832
Random Seed: 166
[Fold 1] Epoch 094 | TrainLoss 0.000121698 | ValLoss 6.84378e-05 | Duration 0:00:01.114873
Random Seed: 166
[Fold 1] Epoch 095 | TrainLoss 0.000121509 | ValLoss 6.84363e-05 | Duration 0:00:01.114139
Random Seed: 166
[Fold 1] Epoch 096 | TrainLoss 0.000121319 | ValLoss 6.84349e-05 | Duration 0:00:01.119751
Random Seed: 166
[Fold 1] Epoch 097 | TrainLoss 0.000121128 | ValLoss 6.84334e-05 | Duration 0:00:01.308972
Random Seed: 166
[Fold 1] Epoch 098 | TrainLoss 0.000120937 | ValLoss 6.8432e-05 | Duration 0:00:01.400973
Random Seed: 166
[Fold 1] Epoch 099 | TrainLoss 0.000120745 | ValLoss 6.84305e-05 | Duration 0:00:01.132719
[Fold 1] Saved best model to models/wfv_fold_1_best.pt

=== WFV Fold 1 RESULT ===
Thr 0.0012246 | TestLoss 4.0647e-05 | Equity 325.20 | Acc 47.43% | Traded 369

Random Seed: 166
[Fold 2] Epoch 000 | TrainLoss 0.000244083 | ValLoss 4.59077e-05 | Duration 0:00:01.143766
Random Seed: 166
[Fold 2] Epoch 001 | TrainLoss 7.94247e-05 | ValLoss 4.23181e-05 | Duration 0:00:01.114101
Random Seed: 166
[Fold 2] Epoch 002 | TrainLoss 6.98042e-05 | ValLoss 4.36082e-05 | Duration 0:00:01.104639
Random Seed: 166
[Fold 2] Epoch 003 | TrainLoss 6.67267e-05 | ValLoss 4.41985e-05 | Duration 0:00:01.155581
Random Seed: 166
[Fold 2] Epoch 004 | TrainLoss 6.53903e-05 | ValLoss 4.37618e-05 | Duration 0:00:01.120293
Random Seed: 166
[Fold 2] Epoch 005 | TrainLoss 6.46722e-05 | ValLoss 4.30821e-05 | Duration 0:00:01.121125
Random Seed: 166
[Fold 2] Epoch 006 | TrainLoss 6.42223e-05 | ValLoss 4.26549e-05 | Duration 0:00:01.269734
Random Seed: 166
[Fold 2] Epoch 007 | TrainLoss 6.3906e-05 | ValLoss 4.25525e-05 | Duration 0:00:01.413171
Random Seed: 166
[Fold 2] Epoch 008 | TrainLoss 6.36645e-05 | ValLoss 4.26888e-05 | Duration 0:00:01.120961
Random Seed: 166
[Fold 2] Epoch 009 | TrainLoss 6.34696e-05 | ValLoss 4.29569e-05 | Duration 0:00:01.107891
Random Seed: 166
[Fold 2] Epoch 010 | TrainLoss 6.33055e-05 | ValLoss 4.32669e-05 | Duration 0:00:01.111149
Random Seed: 166
[Fold 2] Epoch 011 | TrainLoss 6.31623e-05 | ValLoss 4.35564e-05 | Duration 0:00:01.124309
Random Seed: 166
[Fold 2] Epoch 012 | TrainLoss 6.3034e-05 | ValLoss 4.3796e-05 | Duration 0:00:01.132112
Random Seed: 166
[Fold 2] Epoch 013 | TrainLoss 6.29172e-05 | ValLoss 4.39836e-05 | Duration 0:00:01.118926
Random Seed: 166
[Fold 2] Epoch 014 | TrainLoss 6.28094e-05 | ValLoss 4.41278e-05 | Duration 0:00:01.119546
Random Seed: 166
[Fold 2] Epoch 015 | TrainLoss 6.27091e-05 | ValLoss 4.4238e-05 | Duration 0:00:01.124155
Random Seed: 166
[Fold 2] Epoch 016 | TrainLoss 6.26147e-05 | ValLoss 4.43218e-05 | Duration 0:00:01.179345
Random Seed: 166
[Fold 2] Epoch 017 | TrainLoss 6.25253e-05 | ValLoss 4.43859e-05 | Duration 0:00:01.383486
Random Seed: 166
[Fold 2] Epoch 018 | TrainLoss 6.24404e-05 | ValLoss 4.44362e-05 | Duration 0:00:01.259169
Random Seed: 166
[Fold 2] Epoch 019 | TrainLoss 6.23595e-05 | ValLoss 4.44771e-05 | Duration 0:00:01.113616
Random Seed: 166
[Fold 2] Epoch 020 | TrainLoss 6.22819e-05 | ValLoss 4.45106e-05 | Duration 0:00:01.583966
Random Seed: 166
[Fold 2] Epoch 021 | TrainLoss 6.22072e-05 | ValLoss 4.45384e-05 | Duration 0:00:01.130957
Random Seed: 166
[Fold 2] Epoch 022 | TrainLoss 6.21349e-05 | ValLoss 4.45619e-05 | Duration 0:00:01.123921
Random Seed: 166
[Fold 2] Epoch 023 | TrainLoss 6.20645e-05 | ValLoss 4.45816e-05 | Duration 0:00:01.140894
Random Seed: 166
[Fold 2] Epoch 024 | TrainLoss 6.19957e-05 | ValLoss 4.45987e-05 | Duration 0:00:01.127605
Random Seed: 166
[Fold 2] Epoch 025 | TrainLoss 6.19283e-05 | ValLoss 4.4614e-05 | Duration 0:00:01.144571
Random Seed: 166
[Fold 2] Epoch 026 | TrainLoss 6.18621e-05 | ValLoss 4.46278e-05 | Duration 0:00:01.210498
Random Seed: 166
[Fold 2] Epoch 027 | TrainLoss 6.17972e-05 | ValLoss 4.46402e-05 | Duration 0:00:01.410196
Random Seed: 166
[Fold 2] Epoch 028 | TrainLoss 6.17334e-05 | ValLoss 4.46512e-05 | Duration 0:00:01.202031
Random Seed: 166
[Fold 2] Epoch 029 | TrainLoss 6.16708e-05 | ValLoss 4.46604e-05 | Duration 0:00:01.143607
Random Seed: 166
[Fold 2] Epoch 030 | TrainLoss 6.16093e-05 | ValLoss 4.46674e-05 | Duration 0:00:01.120060
Random Seed: 166
[Fold 2] Epoch 031 | TrainLoss 6.15489e-05 | ValLoss 4.4672e-05 | Duration 0:00:01.112748
Random Seed: 166
[Fold 2] Epoch 032 | TrainLoss 6.14896e-05 | ValLoss 4.46743e-05 | Duration 0:00:01.111587
Random Seed: 166
[Fold 2] Epoch 033 | TrainLoss 6.14312e-05 | ValLoss 4.4674e-05 | Duration 0:00:01.128111
Random Seed: 166
[Fold 2] Epoch 034 | TrainLoss 6.13738e-05 | ValLoss 4.46715e-05 | Duration 0:00:01.352407
Random Seed: 166
[Fold 2] Epoch 035 | TrainLoss 6.13173e-05 | ValLoss 4.46668e-05 | Duration 0:00:01.589373
Random Seed: 166
[Fold 2] Epoch 036 | TrainLoss 6.12616e-05 | ValLoss 4.46602e-05 | Duration 0:00:01.272571
Random Seed: 166
[Fold 2] Epoch 037 | TrainLoss 6.12066e-05 | ValLoss 4.46515e-05 | Duration 0:00:01.448916
Random Seed: 166
[Fold 2] Epoch 038 | TrainLoss 6.11524e-05 | ValLoss 4.4641e-05 | Duration 0:00:01.127326
Random Seed: 166
[Fold 2] Epoch 039 | TrainLoss 6.10989e-05 | ValLoss 4.4629e-05 | Duration 0:00:01.100630
Random Seed: 166
[Fold 2] Epoch 040 | TrainLoss 6.10461e-05 | ValLoss 4.46154e-05 | Duration 0:00:01.114643
Random Seed: 166
[Fold 2] Epoch 041 | TrainLoss 6.09939e-05 | ValLoss 4.46005e-05 | Duration 0:00:01.136156
Random Seed: 166
[Fold 2] Epoch 042 | TrainLoss 6.09423e-05 | ValLoss 4.45845e-05 | Duration 0:00:01.123436
Random Seed: 166
[Fold 2] Epoch 043 | TrainLoss 6.08912e-05 | ValLoss 4.45675e-05 | Duration 0:00:01.120115
Random Seed: 166
[Fold 2] Epoch 044 | TrainLoss 6.08407e-05 | ValLoss 4.45497e-05 | Duration 0:00:01.115044
Random Seed: 166
[Fold 2] Epoch 045 | TrainLoss 6.07906e-05 | ValLoss 4.4531e-05 | Duration 0:00:01.108490
Random Seed: 166
[Fold 2] Epoch 046 | TrainLoss 6.07409e-05 | ValLoss 4.45118e-05 | Duration 0:00:01.257891
Random Seed: 166
[Fold 2] Epoch 047 | TrainLoss 6.06917e-05 | ValLoss 4.4492e-05 | Duration 0:00:01.393287
Random Seed: 166
[Fold 2] Epoch 048 | TrainLoss 6.06428e-05 | ValLoss 4.4472e-05 | Duration 0:00:01.239812
Random Seed: 166
[Fold 2] Epoch 049 | TrainLoss 6.05943e-05 | ValLoss 4.44517e-05 | Duration 0:00:01.114536
Random Seed: 166
[Fold 2] Epoch 050 | TrainLoss 6.0546e-05 | ValLoss 4.44311e-05 | Duration 0:00:01.140258
Random Seed: 166
[Fold 2] Epoch 051 | TrainLoss 6.0498e-05 | ValLoss 4.44103e-05 | Duration 0:00:01.146147
Random Seed: 166
[Fold 2] Epoch 052 | TrainLoss 6.04503e-05 | ValLoss 4.43895e-05 | Duration 0:00:01.126843
Random Seed: 166
[Fold 2] Epoch 053 | TrainLoss 6.04028e-05 | ValLoss 4.43686e-05 | Duration 0:00:01.128254
Random Seed: 166
[Fold 2] Epoch 054 | TrainLoss 6.03555e-05 | ValLoss 4.43477e-05 | Duration 0:00:01.144972
Random Seed: 166
[Fold 2] Epoch 055 | TrainLoss 6.03084e-05 | ValLoss 4.43269e-05 | Duration 0:00:01.139855
Random Seed: 166
[Fold 2] Epoch 056 | TrainLoss 6.02614e-05 | ValLoss 4.43062e-05 | Duration 0:00:01.110505
Random Seed: 166
[Fold 2] Epoch 057 | TrainLoss 6.02146e-05 | ValLoss 4.42855e-05 | Duration 0:00:01.380952
Random Seed: 166
[Fold 2] Epoch 058 | TrainLoss 6.01679e-05 | ValLoss 4.42649e-05 | Duration 0:00:01.304638
Random Seed: 166
[Fold 2] Epoch 059 | TrainLoss 6.01213e-05 | ValLoss 4.42445e-05 | Duration 0:00:01.099467
Random Seed: 166
[Fold 2] Epoch 060 | TrainLoss 6.00748e-05 | ValLoss 4.42243e-05 | Duration 0:00:01.110532
Random Seed: 166
[Fold 2] Epoch 061 | TrainLoss 6.00284e-05 | ValLoss 4.42042e-05 | Duration 0:00:01.118713
Random Seed: 166
[Fold 2] Epoch 062 | TrainLoss 5.99821e-05 | ValLoss 4.41844e-05 | Duration 0:00:01.099965
Random Seed: 166
[Fold 2] Epoch 063 | TrainLoss 5.99359e-05 | ValLoss 4.41649e-05 | Duration 0:00:01.140632
Random Seed: 166
[Fold 2] Epoch 064 | TrainLoss 5.98897e-05 | ValLoss 4.41455e-05 | Duration 0:00:01.137862
Random Seed: 166
[Fold 2] Epoch 065 | TrainLoss 5.98436e-05 | ValLoss 4.41264e-05 | Duration 0:00:01.131484
Random Seed: 166
[Fold 2] Epoch 066 | TrainLoss 5.97976e-05 | ValLoss 4.41076e-05 | Duration 0:00:01.108791
Random Seed: 166
[Fold 2] Epoch 067 | TrainLoss 5.97517e-05 | ValLoss 4.40892e-05 | Duration 0:00:01.275211
Random Seed: 166
[Fold 2] Epoch 068 | TrainLoss 5.97058e-05 | ValLoss 4.4071e-05 | Duration 0:00:01.404437
Random Seed: 166
[Fold 2] Epoch 069 | TrainLoss 5.966e-05 | ValLoss 4.40531e-05 | Duration 0:00:01.104920
Random Seed: 166
[Fold 2] Epoch 070 | TrainLoss 5.96143e-05 | ValLoss 4.40357e-05 | Duration 0:00:01.117509
Random Seed: 166
[Fold 2] Epoch 071 | TrainLoss 5.95687e-05 | ValLoss 4.40185e-05 | Duration 0:00:01.121235
Random Seed: 166
[Fold 2] Epoch 072 | TrainLoss 5.95231e-05 | ValLoss 4.40017e-05 | Duration 0:00:01.139898
Random Seed: 166
[Fold 2] Epoch 073 | TrainLoss 5.94775e-05 | ValLoss 4.39853e-05 | Duration 0:00:01.137039
Random Seed: 166
[Fold 2] Epoch 074 | TrainLoss 5.94321e-05 | ValLoss 4.39693e-05 | Duration 0:00:01.130729
Random Seed: 166
[Fold 2] Epoch 075 | TrainLoss 5.93866e-05 | ValLoss 4.39537e-05 | Duration 0:00:01.119169
Random Seed: 166
[Fold 2] Epoch 076 | TrainLoss 5.93413e-05 | ValLoss 4.39385e-05 | Duration 0:00:01.144504
Random Seed: 166
[Fold 2] Epoch 077 | TrainLoss 5.9296e-05 | ValLoss 4.39237e-05 | Duration 0:00:01.217173
Random Seed: 166
[Fold 2] Epoch 078 | TrainLoss 5.92507e-05 | ValLoss 4.39093e-05 | Duration 0:00:01.441858
Random Seed: 166
[Fold 2] Epoch 079 | TrainLoss 5.92055e-05 | ValLoss 4.38954e-05 | Duration 0:00:01.174511
Random Seed: 166
[Fold 2] Epoch 080 | TrainLoss 5.91603e-05 | ValLoss 4.38818e-05 | Duration 0:00:01.126006
Random Seed: 166
[Fold 2] Epoch 081 | TrainLoss 5.91152e-05 | ValLoss 4.38687e-05 | Duration 0:00:01.151370
Random Seed: 166
[Fold 2] Epoch 082 | TrainLoss 5.90701e-05 | ValLoss 4.3856e-05 | Duration 0:00:01.120498
Random Seed: 166
[Fold 2] Epoch 083 | TrainLoss 5.90251e-05 | ValLoss 4.38437e-05 | Duration 0:00:01.119770
Random Seed: 166
[Fold 2] Epoch 084 | TrainLoss 5.898e-05 | ValLoss 4.38318e-05 | Duration 0:00:01.126349
Random Seed: 166
[Fold 2] Epoch 085 | TrainLoss 5.8935e-05 | ValLoss 4.38204e-05 | Duration 0:00:01.117667
Random Seed: 166
[Fold 2] Epoch 086 | TrainLoss 5.889e-05 | ValLoss 4.38096e-05 | Duration 0:00:01.131119
Random Seed: 166
[Fold 2] Epoch 087 | TrainLoss 5.8845e-05 | ValLoss 4.3799e-05 | Duration 0:00:01.151350
Random Seed: 166
[Fold 2] Epoch 088 | TrainLoss 5.88001e-05 | ValLoss 4.3789e-05 | Duration 0:00:01.376389
Random Seed: 166
[Fold 2] Epoch 089 | TrainLoss 5.87551e-05 | ValLoss 4.37796e-05 | Duration 0:00:01.309316
Random Seed: 166
[Fold 2] Epoch 090 | TrainLoss 5.87101e-05 | ValLoss 4.37707e-05 | Duration 0:00:01.129426
Random Seed: 166
[Fold 2] Epoch 091 | TrainLoss 5.86652e-05 | ValLoss 4.37624e-05 | Duration 0:00:01.127252
Random Seed: 166
[Fold 2] Epoch 092 | TrainLoss 5.86202e-05 | ValLoss 4.37545e-05 | Duration 0:00:01.127286
Random Seed: 166
[Fold 2] Epoch 093 | TrainLoss 5.85752e-05 | ValLoss 4.37472e-05 | Duration 0:00:01.120419
Random Seed: 166
[Fold 2] Epoch 094 | TrainLoss 5.85302e-05 | ValLoss 4.37405e-05 | Duration 0:00:01.121030
Random Seed: 166
[Fold 2] Epoch 095 | TrainLoss 5.84851e-05 | ValLoss 4.37344e-05 | Duration 0:00:01.120782
Random Seed: 166
[Fold 2] Epoch 096 | TrainLoss 5.84401e-05 | ValLoss 4.37289e-05 | Duration 0:00:01.134608
Random Seed: 166
[Fold 2] Epoch 097 | TrainLoss 5.8395e-05 | ValLoss 4.37237e-05 | Duration 0:00:01.119682
Random Seed: 166
[Fold 2] Epoch 098 | TrainLoss 5.83499e-05 | ValLoss 4.37193e-05 | Duration 0:00:01.334851
Random Seed: 166
[Fold 2] Epoch 099 | TrainLoss 5.83048e-05 | ValLoss 4.37153e-05 | Duration 0:00:01.399291
[Fold 2] Saved best model to models/wfv_fold_2_best.pt

=== WFV Fold 2 RESULT ===
Thr 0.00247236 | TestLoss 0.000103436 | Equity -22.92 | Acc 48.96% | Traded 768

Random Seed: 166
[Fold 3] Epoch 000 | TrainLoss 0.000223929 | ValLoss 0.000113135 | Duration 0:00:01.126289
Random Seed: 166
[Fold 3] Epoch 001 | TrainLoss 6.36913e-05 | ValLoss 0.000101905 | Duration 0:00:01.151372
Random Seed: 166
[Fold 3] Epoch 002 | TrainLoss 5.2442e-05 | ValLoss 0.000100011 | Duration 0:00:01.122710
Random Seed: 166
[Fold 3] Epoch 003 | TrainLoss 4.90058e-05 | ValLoss 9.94024e-05 | Duration 0:00:01.125968
Random Seed: 166
[Fold 3] Epoch 004 | TrainLoss 4.76926e-05 | ValLoss 9.92991e-05 | Duration 0:00:01.137736
Random Seed: 166
[Fold 3] Epoch 005 | TrainLoss 4.7056e-05 | ValLoss 9.94502e-05 | Duration 0:00:01.118297
Random Seed: 166
[Fold 3] Epoch 006 | TrainLoss 4.66759e-05 | ValLoss 9.95477e-05 | Duration 0:00:01.128890
Random Seed: 166
[Fold 3] Epoch 007 | TrainLoss 4.64169e-05 | ValLoss 9.95703e-05 | Duration 0:00:01.307303
Random Seed: 166
[Fold 3] Epoch 008 | TrainLoss 4.62239e-05 | ValLoss 9.95887e-05 | Duration 0:00:01.404767
Random Seed: 166
[Fold 3] Epoch 009 | TrainLoss 4.60694e-05 | ValLoss 9.96207e-05 | Duration 0:00:01.106486
Random Seed: 166
[Fold 3] Epoch 010 | TrainLoss 4.59391e-05 | ValLoss 9.96555e-05 | Duration 0:00:01.108516
Random Seed: 166
[Fold 3] Epoch 011 | TrainLoss 4.58248e-05 | ValLoss 9.96797e-05 | Duration 0:00:01.115962
Random Seed: 166
[Fold 3] Epoch 012 | TrainLoss 4.57213e-05 | ValLoss 9.96904e-05 | Duration 0:00:01.119925
Random Seed: 166
[Fold 3] Epoch 013 | TrainLoss 4.5626e-05 | ValLoss 9.96949e-05 | Duration 0:00:01.099774
Random Seed: 166
[Fold 3] Epoch 014 | TrainLoss 4.55376e-05 | ValLoss 9.97004e-05 | Duration 0:00:01.119793
Random Seed: 166
[Fold 3] Epoch 015 | TrainLoss 4.5455e-05 | ValLoss 9.97106e-05 | Duration 0:00:01.145072
Random Seed: 166
[Fold 3] Epoch 016 | TrainLoss 4.53775e-05 | ValLoss 9.97281e-05 | Duration 0:00:01.107198
Random Seed: 166
[Fold 3] Epoch 017 | TrainLoss 4.53046e-05 | ValLoss 9.97541e-05 | Duration 0:00:01.228749
Random Seed: 166
[Fold 3] Epoch 018 | TrainLoss 4.52355e-05 | ValLoss 9.9788e-05 | Duration 0:00:01.410669
Random Seed: 166
[Fold 3] Epoch 019 | TrainLoss 4.51695e-05 | ValLoss 9.98289e-05 | Duration 0:00:01.179413
Random Seed: 166
[Fold 3] Epoch 020 | TrainLoss 4.51061e-05 | ValLoss 9.9876e-05 | Duration 0:00:01.117442
Random Seed: 166
[Fold 3] Epoch 021 | TrainLoss 4.50448e-05 | ValLoss 9.99286e-05 | Duration 0:00:01.102456
Random Seed: 166
[Fold 3] Epoch 022 | TrainLoss 4.49852e-05 | ValLoss 9.99861e-05 | Duration 0:00:01.122643
Random Seed: 166
[Fold 3] Epoch 023 | TrainLoss 4.49269e-05 | ValLoss 0.000100048 | Duration 0:00:01.127397
Random Seed: 166
[Fold 3] Epoch 024 | TrainLoss 4.48694e-05 | ValLoss 0.000100114 | Duration 0:00:01.136758
Random Seed: 166
[Fold 3] Epoch 025 | TrainLoss 4.48125e-05 | ValLoss 0.000100185 | Duration 0:00:01.099298
Random Seed: 166
[Fold 3] Epoch 026 | TrainLoss 4.47561e-05 | ValLoss 0.00010026 | Duration 0:00:01.089115
Random Seed: 166
[Fold 3] Epoch 027 | TrainLoss 4.47e-05 | ValLoss 0.000100339 | Duration 0:00:01.126482
Random Seed: 166
[Fold 3] Epoch 028 | TrainLoss 4.46444e-05 | ValLoss 0.000100419 | Duration 0:00:01.334094
Random Seed: 166
[Fold 3] Epoch 029 | TrainLoss 4.45894e-05 | ValLoss 0.0001005 | Duration 0:00:01.330589
Random Seed: 166
[Fold 3] Epoch 030 | TrainLoss 4.45353e-05 | ValLoss 0.000100581 | Duration 0:00:01.114407
Random Seed: 166
[Fold 3] Epoch 031 | TrainLoss 4.44822e-05 | ValLoss 0.000100662 | Duration 0:00:01.128146
Random Seed: 166
[Fold 3] Epoch 032 | TrainLoss 4.44302e-05 | ValLoss 0.000100744 | Duration 0:00:01.144642
Random Seed: 166
[Fold 3] Epoch 033 | TrainLoss 4.43791e-05 | ValLoss 0.000100825 | Duration 0:00:01.142909
Random Seed: 166
[Fold 3] Epoch 034 | TrainLoss 4.4329e-05 | ValLoss 0.000100906 | Duration 0:00:01.116533
Random Seed: 166
[Fold 3] Epoch 035 | TrainLoss 4.42798e-05 | ValLoss 0.000100986 | Duration 0:00:01.108117
Random Seed: 166
[Fold 3] Epoch 036 | TrainLoss 4.42313e-05 | ValLoss 0.000101065 | Duration 0:00:01.117902
Random Seed: 166
[Fold 3] Epoch 037 | TrainLoss 4.41836e-05 | ValLoss 0.000101143 | Duration 0:00:01.113818
Random Seed: 166
[Fold 3] Epoch 038 | TrainLoss 4.41366e-05 | ValLoss 0.00010122 | Duration 0:00:01.274384
Random Seed: 166
[Fold 3] Epoch 039 | TrainLoss 4.40901e-05 | ValLoss 0.000101297 | Duration 0:00:01.405832
Random Seed: 166
[Fold 3] Epoch 040 | TrainLoss 4.40442e-05 | ValLoss 0.000101373 | Duration 0:00:01.130037
Random Seed: 166
[Fold 3] Epoch 041 | TrainLoss 4.39989e-05 | ValLoss 0.000101448 | Duration 0:00:01.151705
Random Seed: 166
[Fold 3] Epoch 042 | TrainLoss 4.3954e-05 | ValLoss 0.000101522 | Duration 0:00:01.118872
Random Seed: 166
[Fold 3] Epoch 043 | TrainLoss 4.39096e-05 | ValLoss 0.000101596 | Duration 0:00:01.161921
Random Seed: 166

In [33]:
eqs = [r["equity"] for r in wf_results]
print("Folds:", len(wf_results))
print("Mean final equity:", np.mean(eqs))
print("Median final equity:", np.median(eqs))
print("Profitable folds:", sum(e > 1000 for e in eqs), "/", len(eqs))

Folds: 26
Mean final equity: 600.2328785898907
Median final equity: 729.9482910488202
Profitable folds: 3 / 26